# Generated by Django 5.2.6 on 2025-11-08 18:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]+$', 'Formato de patente inválido')])),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990, 'Año mínimo 1990'), django.core.validators.MaxValueValidator(2025, 'Año máximo 2025')])),
                ('capacidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10, 'Capacidad mínima 10 pasajeros'), django.core.validators.MaxValueValidator(80, 'Capacidad máxima 80 pasajeros')])),
                ('marca', models.CharField(default='Sin especificar', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras')])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel_acceso', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('REPARACION', 'En Reparación'), ('FUERA_SERVICIO', 'Fuera de Servicio'), ('RESERVADO', 'Reservado')], default='OPERATIVO', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now=True)),
                ('kilometraje', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='templatesApp.bus', verbose_name='Bus')),
            ],
            options={
                'verbose_name': 'Estado de Bus',
                'verbose_name_plural': 'Estados de Buses',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras')])),
                ('apellido', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras')])),
                ('direccion', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-]+$', 'Formato de contacto inválido')])),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18, 'Debe ser mayor de 18 años'), django.core.validators.MaxValueValidator(70, 'Edad máxima 70 años')])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['apellido', 'nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('edad__gte', 18), ('edad__lte', 70)), name='edad_valida')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='templatesApp.rol', verbose_name='Rol')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to='templatesApp.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Asignación de Rol',
                'verbose_name_plural': 'Asignaciones de Roles',
                'ordering': ['-fecha_asignacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('trabajador', 'rol'), name='unique_active_rol_asignacion')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('turno', models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], default='MAÑANA', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='templatesApp.bus', verbose_name='Bus')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_bus', to='templatesApp.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Asignación de Bus',
                'verbose_name_plural': 'Asignaciones de Buses',
                'ordering': ['-fecha_asignacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('trabajador', 'bus', 'turno'), name='unique_active_bus_asignacion')],
            },
        ),
    ]
