# Generated by Django 5.2.6 on 2025-10-19 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador_nombre', models.CharField(max_length=100)),
                ('trabajador_apellido', models.CharField(max_length=100)),
                ('trabajador_id', models.PositiveIntegerField()),
                ('bus_patente', models.CharField(max_length=20)),
                ('bus_modelo', models.CharField(max_length=100)),
                ('bus_id', models.PositiveIntegerField()),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('turno', models.CharField(choices=[('MAÑANA', 'Mañana'), ('TARDE', 'Tarde'), ('NOCHE', 'Noche')], default='MAÑANA', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asignación de Bus',
                'verbose_name_plural': 'Asignaciones de Buses',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador_nombre', models.CharField(max_length=100)),
                ('trabajador_apellido', models.CharField(max_length=100)),
                ('trabajador_id', models.PositiveIntegerField()),
                ('rol_nombre', models.CharField(max_length=100)),
                ('rol_id', models.PositiveIntegerField()),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asignación de Rol',
                'verbose_name_plural': 'Asignaciones de Roles',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]+$', 'Formato de patente inválido')])),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990, 'Año mínimo 1990'), django.core.validators.MaxValueValidator(2025, 'Año máximo 2025')])),
                ('capacidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10, 'Capacidad mínima 10 pasajeros'), django.core.validators.MaxValueValidator(80, 'Capacidad máxima 80 pasajeros')])),
                ('marca', models.CharField(default='Sin especificar', max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='EstadoBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_patente', models.CharField(max_length=20, unique=True)),
                ('bus_modelo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('REPARACION', 'En Reparación'), ('FUERA_SERVICIO', 'Fuera de Servicio'), ('RESERVADO', 'Reservado')], default='OPERATIVO', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now=True)),
                ('kilometraje', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estado de Bus',
                'verbose_name_plural': 'Estados de Buses',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras')])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel_acceso', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras')])),
                ('apellido', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras')])),
                ('direccion', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-]+$', 'Formato de contacto inválido')])),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18, 'Debe ser mayor de 18 años'), django.core.validators.MaxValueValidator(70, 'Edad máxima 70 años')])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
